### ISSUE TITLE
Broken Links in Installation Instructions

### ISSUE THREAD

**Issue by DarioS** [statisticalbiotechnology/diffacto#18]
When I click on Anaconda, I get an error. When I click on pyteomics, I also get an error. They need updating to valid URLs.

**Comment by percolator** [comment]
Hi Dario,

What do you mean with "clicking" pyteomics?

Yours
--Lukas

**Comment by DarioS** [comment]
When a user first arrives at the GitHub website of Diffacto, they see README.rst which seems to have outdated hyperlinks to click.

**Comment by percolator** [comment]
Thanks, the links are now updated!
