### ISSUE TITLE
Imputation Algorithm Not Documented

### ISSUE THREAD

**Issue by DarioS** [statisticalbiotechnology/diffacto#23]
Neither the journal article nor this website gives a formulaic definition of Diffacto's imputation process. When I set `-impute_threshold 1.1` to effectively turn off imputation, somehow it makes a large difference to the result matrix. On default, I get a 100% complete matrix, but with imputation turned off, I get an average of 17% missing values per protein, I wouldn't think that there's much range between 99% and 100%, but it seems there is a lot. A formula would help users understand it.

**Comment by percolator** [comment]
Hi Dario,

I am not sure there is much a formula would help you with. The amount of
missing values are calculated per sample group, which might explain some of
the differences you observe. Could it be that you have several sample
groups, and in your 17% missing values there is one sample group with only
missing values?

--Lukas

**Comment by DarioS** [comment]
I have 70 patients and 140 samples (two technical replicates each). I should use `-samples` to group them. It makes sense that some patients don't express some proteins. I was wrongly thinking a group was a set of different samples for a particular peptide.

**Comment by percolator** [comment]
That makes sense. Thanks! --Lukas
